-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 22:54:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Login` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `Log_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Log_nome` VARCHAR(45) NOT NULL,
  `Log_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Log_nregisto`),
  UNIQUE INDEX `Log_nome_UNIQUE` (`Log_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participantes` (
  `Par_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Par_Log_nregisto` INT NOT NULL,
  `Par_nome` VARCHAR(45) NOT NULL,
  `Par_idade` TINYINT(1) NULL,
  PRIMARY KEY (`Par_nregisto`),
  UNIQUE INDEX `Par_Log_nregisto_UNIQUE` (`Par_Log_nregisto` ASC),
  CONSTRAINT `Par_Log_nregisto`
    FOREIGN KEY (`Par_Log_nregisto`)
    REFERENCES `mydb`.`Login` (`Log_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Eventos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `Eve_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Eve_nome` VARCHAR(45) NOT NULL,
  `Eve_data` DATE NOT NULL,
  `Eve_local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Eve_nregisto`),
  UNIQUE INDEX `Eve_nome_UNIQUE` (`Eve_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Oradores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Oradores` (
  `Ora_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Ora_Log_nregisto` INT NOT NULL,
  `Ora_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ora_nregisto`),
  UNIQUE INDEX `Ora_Log_nregisto_UNIQUE` (`Ora_Log_nregisto` ASC),
  CONSTRAINT `Ora_Log_nregisto`
    FOREIGN KEY (`Ora_Log_nregisto`)
    REFERENCES `mydb`.`Login` (`Log_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atividades` (
  `Ati_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Ati_sala` VARCHAR(45) NOT NULL,
  `Ati_começo` DATETIME NULL,
  `Ati_final` DATETIME NULL,
  `Ati_Eve_nregisto` INT NOT NULL,
  `Ati_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ati_nregisto`),
  UNIQUE INDEX `Ati_sala_UNIQUE` (`Ati_sala` ASC),
  INDEX `Ati_Eve_nregisto_idx` (`Ati_Eve_nregisto` ASC),
  CONSTRAINT `Ati_Eve_nregisto`
    FOREIGN KEY (`Ati_Eve_nregisto`)
    REFERENCES `mydb`.`Eventos` (`Eve_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patrocinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Patrocinadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Patrocinadores` (
  `Pat_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Pat_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pat_nregisto`),
  UNIQUE INDEX `Pat_marca_UNIQUE` (`Pat_marca` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Temas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Temas` (
  `Tem_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Tem_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tem_nregisto`),
  UNIQUE INDEX `Tem_nome_UNIQUE` (`Tem_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inscritos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inscritos` (
  `Ins_Par_nregisto` INT NOT NULL,
  `Ins_Ati_registo` INT NOT NULL,
  `Ins_avaliação` VARCHAR(15) NULL,
  PRIMARY KEY (`Ins_Par_nregisto`, `Ins_Ati_registo`),
  INDEX `Ins_Ati_nregisto_idx` (`Ins_Ati_registo` ASC),
  CONSTRAINT `Ins_Par_nregisto`
    FOREIGN KEY (`Ins_Par_nregisto`)
    REFERENCES `mydb`.`Participantes` (`Par_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ins_Ati_nregisto`
    FOREIGN KEY (`Ins_Ati_registo`)
    REFERENCES `mydb`.`Atividades` (`Ati_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organizadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Organizadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Organizadores` (
  `Org_Ora_nregisto` INT NOT NULL,
  `Org_Ati_nregisto` INT NOT NULL,
  PRIMARY KEY (`Org_Ora_nregisto`, `Org_Ati_nregisto`),
  INDEX `Org_Ati_nregisto_idx` (`Org_Ati_nregisto` ASC),
  CONSTRAINT `Org_Ora_nregisto`
    FOREIGN KEY (`Org_Ora_nregisto`)
    REFERENCES `mydb`.`Oradores` (`Ora_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Org_Ati_nregisto`
    FOREIGN KEY (`Org_Ati_nregisto`)
    REFERENCES `mydb`.`Atividades` (`Ati_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conteudos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Conteudos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Conteudos` (
  `Con_Eve_nregisto` INT NOT NULL,
  `Con_Tem_nregisto` INT NOT NULL,
  PRIMARY KEY (`Con_Eve_nregisto`, `Con_Tem_nregisto`),
  INDEX `Con_Tem_nregisto_idx` (`Con_Tem_nregisto` ASC),
  CONSTRAINT `Con_Eve_nregisto`
    FOREIGN KEY (`Con_Eve_nregisto`)
    REFERENCES `mydb`.`Eventos` (`Eve_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Con_Tem_nregisto`
    FOREIGN KEY (`Con_Tem_nregisto`)
    REFERENCES `mydb`.`Temas` (`Tem_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patrocinios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Patrocinios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Patrocinios` (
  `Patr_Pat_nregisto` INT NOT NULL,
  `Patr_Eve_nregisto` INT NOT NULL,
  PRIMARY KEY (`Patr_Pat_nregisto`, `Patr_Eve_nregisto`),
  INDEX `Patr_Eve_nregisto_idx` (`Patr_Eve_nregisto` ASC),
  CONSTRAINT `Patr_Pat_nregisto`
    FOREIGN KEY (`Patr_Pat_nregisto`)
    REFERENCES `mydb`.`Patrocinadores` (`Pat_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Patr_Eve_nregisto`
    FOREIGN KEY (`Patr_Eve_nregisto`)
    REFERENCES `mydb`.`Eventos` (`Eve_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vencedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vencedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vencedores` (
  `Ven_nregisto` INT NOT NULL AUTO_INCREMENT,
  `Ven_Par_nregisto` INT NULL,
  `Ven_Ati_nregisto` INT NULL,
  PRIMARY KEY (`Ven_nregisto`),
  INDEX `Ven_Par_nregisto_idx` (`Ven_Par_nregisto` ASC),
  INDEX `Ven_Ati_nregisto_idx` (`Ven_Ati_nregisto` ASC),
  CONSTRAINT `Ven_Par_nregisto`
    FOREIGN KEY (`Ven_Par_nregisto`)
    REFERENCES `mydb`.`Inscritos` (`Ins_Par_nregisto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ven_Ati_nregisto`
    FOREIGN KEY (`Ven_Ati_nregisto`)
    REFERENCES `mydb`.`Inscritos` (`Ins_Ati_registo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
